# This file defines the constants used in the whole package

ACTION = "action"
ADAPTER = "adapter"
AGENT = "agent"
AGENT_ROT = "agent_rot"
AGENT_POS = "agent_pos"
AGENT_START_POS ="agent_start_pos"
ALL = "all"
AUTOREGRESSIVE = "autoregressive"

BABBAGE_002 = "babbage-002"
BASE_PROMPT = "base_prompt"
BASE_PROMPT_SEARCH = "base_prompt_search"

CACHE = "cache"
COARSE_OCCUPANCY = "coarse_occupancy"
COLLISION = "collision"
CONTENT = "content"
CONTEXT_PLACEHOLDER = "context_placeholder"
CONTRACT = "contract"
CORRECT_MAPPING = "correct_mapping"
CORRECT_OBJ = "correct_objects"
COS_EOR = "cos_eor"
COUNT_CORRECT = "count_correct"
COUNT_WRONG = "count_wrong"
CUDA_VISIBLE_DEVICES = "CUDA_VISIBLE_DEVICES"
CURRENT_MAPPING = "current_mapping"
CUR_VISIBLE_OBJ_KEYS = "cur_visible_obj_keys"
CUR_VISIBLE_REC_KEYS = "cur_visible_rec_keys"

DEMO = "demo"
DONE = "done"
DOOR = "door"

END = "end"
EXAMPLE_PLACEHOLDER = "example_placeholder"
EXAMPLE_PICK = "example_pick"
EXAMPLE_EXPLORE = "example_explore"
EXPAND = "expand"

FEEDBACK_PLACEHOLDER = "feedback_placeholder"

GRAPH = "graph"
GRAPH_PLACEHOLDER = "graph_placeholder"
GRIPPED_OBJ_KEY = "gripped_obj_key"

IID = "iid" # instance id
INSTANCE_ID_COUNT = "instance_id_count"

DELTA = "delta"
DEPTH = "depth"
DEVICE = "device"

EXP = "exploring"

FAIL = "failed"
FAIL_THRESHOLD = "fail_threshold"
FLAG = "flag"
FRONTIER = "frontier"

GPS_COMPASS = "gps_compass"
GPT_35_TURBO = "gpt-3.5-turbo"
GPT_35_TURBO_INSTRUCT = "gpt-3.5-turbo-instruct"
GPT_4 = "gpt-4"
GPT2_LARGE = "gpt2-large"
GRIPPED_OBJECT_ID = "gripped_object_id"
GRIPPED_IID = "gripped_iid"
GRIPPED_SID = "gripped_sid"

HF = "hf"
HF_HOME = "HF_HOME"
HIGH_LEVEL = "high_level"

INP = "in-progress"

KEY = "key"

LLAMA = "llama"
LLAMA_2_7B_CHAT_HF = "Llama-2-7b-chat-hf"
LLM = "llm"
LLM_MODEL = "llm_model"
LLMADAPTER = "llmadapter"
LLMZEROSHOT = "llmzeroshot"
LOG_PATH = "log_path"
LOG_PROBS = "logprobs"
LOGS = "logs"
LOOK = "look-at"
LOOK_UP = "look up"
LOOK_DOWN = "look down"
LOW_LEVEL = "low_level"

MANUAL = "manual"
MAX_GRAPH_COMMAND_STEPS = "max_graph_command_steps"
MAX_MEMORY = "max_memory"
MAX_PLAN_RETRIES_FEEDBACK = "max_plan_retries_feedback"
MAX_PROMPT_BUDGET = "max_prompt_budget"
MAX_STEPS = "max_steps"
MAX_STEPS_PER_PROMPT = "max_steps_per_prompt"
MAX_TOKENS = "max_tokens"
MEMORY_PLACEHOLDER = "memory_placeholder"
MISSION_COMPLETE = "mission complete"
MODE = "mode"
MODEL = "model"
MODEL_PATH = "model_path"
MOVE_FORWARD = "move forward"
MSG_PLANNER = "msg_planner"
MULTISTEP = "multistep"

NAME = "name"
NAV = "navigating"
NL = "nl"
NOTHING = "nothing"
NUM_VISIBLE_OBJECTS = "num_visible_objects"
NUM_VISIBLE_RECS = "num_visible_recs"

OBJ = "object"
OBJ_DISCOVERED = "objects_discovered"
OBJ_MOVED = "objects_moved"
OBJECT_KEYS = "object_keys"
OBJECT_POS = "object_pos"
OBJECT_TYPE = "object_type"
ONCE = "once"
OPENAI = "openai"
OPTION = "option"
OPTION_LIST = "option_list"
OPTION_PLACEHOLDER = "option_placeholder"
ORACLE = "oracle"
OUTCOME = "outcome"

PICTURE = "picture"
PLACEHOLDER = "placeholder"
PLACEMENT = "placement"
PLACEMENT_REC = "placement_rec" # objects on the correct rec
PLACEMENT_ROOM = "placement_room" # objects in the correct room
PLATFORM = "platform"
PLANNER = "planner"
PLANNER_CONTEXT_OBS_KEYS = "planner_context_obs_keys"
POS = "pos"
PP = "pick-place"
PREFIX = "prefix"
PREFIX_PLANNER_MSG ="prefix_planner_msg"
PREV_STEPS_ALL = "prev_steps_all"
PREV_STEPS_SUC = "prev_steps_suc"
PREV_STEPS_MSG = "prev_steps_msg"
PRIMITIVE = "primitive"
PROMPT = "prompt"
PROMPT_THRESHOLD = "prompt_threshold"

RAW = "raw"
REC = "receptacle"
REC_DISCOVERED = "recs_discovered"
RECS_KEYS = "recs_keys"
RECS_POS = "recs_pos"
REPLAY = "replay"
RESPONSE = "response"
RGB = "rgb"
ROLE = "role"
ROOM = "room"

SAYCAN = "saycan"
SAYPLAN = "sayplan"
SAMPLING_PARAMS = "sampling_params"
SEARCH = "search"
SEEN_AREA = "seen_area"
SEMANTIC = "semantic"
SEMANTIC_CLASS = "semantic_class"
SEM_CLASS = "sem_class"
SID = "sid" # simulation object id
SIMPLIFY_KEYS = "simplify_keys"
SINGLE = "single"
SKILL_PLACEHOLDER = "skill_placeholder"
SKIP = "skipped"
SNAP_ID_TO_NAVMESH = "snap_id_to_navmesh"
START = "start"
START_MAPPING = "start_mapping"
STEP = "step"
STEP_RAW = "step_raw"
STEP_PARSED = "step_parsed"
SUC = "succeeded"
SYSTEM = "system"
SYSTEM_PROMPT = "system_prompt"
SYSTEM_PROMPT_SEARCH = "system_prompt_search"

TARGET_OBJ = "target_object"
TARGET_TYPE = "target_type"
TARGET_REC = "target_receptacle"
TEST = "test"
TEXT_DAVINCI_002 = "text-davinci-002"
TEXT_DAVINCI_003 = "text-davinci-003"
TIMESTEP = "timestep"
TURN_LEFT = "turn left"
TURN_RIGHT = "turn right"
TRANSFORMERS_CACHE = "TRANSFORMERS_CACHE"
TYPE = "type"

USER = "user"

VAL = "value"
VISIBLE_OBJECT_IIDS = "visible_object_iids"
VISIBLE_OBJECT_SIDS = "visible_obj_sids"
VISIBLE_REC_IIDS = "visible_rec_iids"
VISIBLE_REC_SIDS = "visible_rec_sids"

WINDOW = "window"
WRONG_OBJ = "wrong_objects"


# commonly used prefix and postfixes

def postfix_placeholder(val: str) -> str:
    return val + f"_{PLACEHOLDER}"
    